### ISSUE TITLE
Manual install overwritten by consult role

### ISSUE THREAD

**Issue by include** [robertdebock/ansible-role-consul#4]
## Describe the bug

I managed to install this consul dependency via the main role hashicorp.  It is a manual install of an Arm64 consul version but, for moments I see the desired version installed and working but a few seconds later consul role kicks-in and installs an older version via apt.

There is no error running the playbook.

- Control node OS: macOs
- Control node Ansible version: 2.12.2
- Managed node OS:    Ubuntu 21.10

Would appreciate your help.

Thank you,
Francisco

**Comment by robertdebock** [comment]
Hi,

This role indeed installs consul:

```yaml
- name: install consul
  ansible.builtin.package:
    name: consul
    state: present
```

But, as you can see; no version is specified. That means; if there is any version installed using a package (apt for example), this task will be "ok", not changing anything.

Arm64 should be available in the repository that is installed using [ansible-role-hashicorp](https://github.com/robertdebock/ansible-role-hashicorp).

In other words, this role is not compatibel with manual installations. Hope this information helps you.

**Comment by robertdebock** [comment]
I'm sorry, I think I answered a bit too quick. Give me some time to analyse this further.

**Comment by robertdebock** [comment]
It should have been compatible, so I'm now changing a couple of roles to allow skipping the installation.

Thanks for you feedback, sorry for my jumping to a conclusion.

I'll get back later with an update.

**Comment by include** [comment]
Hi @robertdebock no worries. I also must start to do better collab to help on what I can.

**Comment by robertdebock** [comment]
You can now skip the installation of the package. Please see `defaults/main.yml` for details.

Let me know if this does not work for you.
